#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# sql-to-erd — wizard do dbview: SQL (ou DBML) -> ERD.
# Instalado no PATH via `npm link` (junto do comando `dbview`).
# Requer: node >= 20 e npx. Git e opcional (conferencia de privacidade).
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Defaults persistentes entre execucoes (caminhos lembrados). Nao e segredo:
# vive fora do repo, em ~/.config. Use DBVIEW_WIZARD_CONFIG para apontar
# para outro arquivo.
ENV_FILE="${DBVIEW_WIZARD_CONFIG:-$HOME/.config/dbview/config}"
mkdir -p "$(dirname "$ENV_FILE")"

have() { command -v "$1" >/dev/null 2>&1; }
_abs() { readlink -f -- "$1" 2>/dev/null || printf '%s' "$1"; }

banner "do SQL ao ERD (dbview)"

# ── Stage 1: ambiente ─────────────────────────────────────────────────────
stage "Ambiente: Node e o dbview"
say "Checando o basico antes de comecar."

if have node; then
  nodev=$(node --version)
  note "node $nodev"
  maj=${nodev#v}; maj=${maj%%.*}
  if (( maj < 20 )); then
    warn "o dbview exige Node >= 20 (encontrado $nodev)."
  fi
else
  warn "node nao esta no PATH. Instale Node >= 20 e rode de novo."
fi

DBVIEW_HOME=$(_existing DBVIEW_HOME || true)
if [[ -z "$DBVIEW_HOME" ]]; then
  DBVIEW_HOME="$HOME/Projects/dbview"
fi
ask DBVIEW_HOME "Pasta do repo dbview:"
if [[ -z "$DBVIEW_HOME" ]]; then
  DBVIEW_HOME="$HOME/Projects/dbview"
fi
DBVIEW_HOME="${DBVIEW_HOME/#\~/$HOME}"
if [[ -f "$DBVIEW_HOME/src/cli.js" ]]; then
  note "ok: $DBVIEW_HOME/src/cli.js"
else
  warn "nao achei $DBVIEW_HOME/src/cli.js"
  step "Clone o dbview nesse caminho (git clone <url> \"$DBVIEW_HOME\") e volte."
  pause "Enter para continuar"
fi
write_env DBVIEW_HOME "$DBVIEW_HOME"

if have dbview; then
  note "comando global 'dbview' ja disponivel"
else
  step "Torne o dbview global (uma vez): npm link dentro do repo."
  if confirm "Rodar 'npm link' agora em $DBVIEW_HOME?"; then
    if (cd "$DBVIEW_HOME" && npm link >/dev/null 2>&1); then
      if have dbview; then
        note "ok: 'dbview' e 'sql-to-erd' agora sao globais"
      else
        warn "link feito, mas 'dbview' nao apareceu no PATH"
      fi
    else
      warn "npm link falhou; rode manualmente e o wizard segue com node direto"
    fi
  fi
fi

# ── Stage 2: entrada ──────────────────────────────────────────────────────
stage "Entrada: qual schema?"
say "Aponte um .sql (sera convertido) ou um .dbml (ja pronto)."
step "Ex.: ./schema.sql  ou  ~/projetos/meu-app/db/schema.sql  (ou ja um .dbml)"
ask ENTRADA "Caminho do .sql ou .dbml:"
ENTRADA="${ENTRADA/#\~/$HOME}"
if [[ -n "$ENTRADA" && ! -f "$ENTRADA" ]]; then
  warn "arquivo nao encontrado: $ENTRADA"
  pause "Enter para seguir mesmo assim"
fi
if [[ -n "$ENTRADA" ]]; then
  write_env ENTRADA "$ENTRADA"
fi

# ── Stage 3: DBML ─────────────────────────────────────────────────────────
stage "DBML: converter ou confirmar"

if [[ "${ENTRADA,,}" == *.dbml ]]; then
  DBML_PATH="$ENTRADA"
  note "a entrada ja e DBML; nada a converter."
else
  DIALETO=$(_existing DIALETO || true)
  if [[ -z "$DIALETO" ]]; then DIALETO=mysql; fi
  ask DIALETO "Dialeto SQL (mysql/postgres/mssql/oracle):"
  if [[ -z "$DIALETO" ]]; then DIALETO=mysql; fi
  write_env DIALETO "$DIALETO"

  dbml_default="${ENTRADA%.*}.dbml"
  cur=$(_existing DBML_PATH || true)
  if [[ -n "$cur" ]]; then
    ask DBML_PATH "Caminho do .dbml (saida):"
  else
    ask DBML_PATH "Caminho do .dbml (saida) [Enter = $dbml_default]:"
  fi
  if [[ -z "$DBML_PATH" ]]; then DBML_PATH="$dbml_default"; fi
  DBML_PATH="${DBML_PATH/#\~/$HOME}"

  say "A conversao usa o parser oficial (@dbml/cli), avulso, via npx — nada instalado no projeto."
  if confirm "Rodar a conversao agora?"; then
    if npx -y -p @dbml/cli sql2dbml "--$DIALETO" "$ENTRADA" -o "$DBML_PATH"; then
      note "ok: $DBML_PATH"
    else
      warn "a conversao falhou; confira o dialeto e os caminhos e tente de novo"
    fi
  fi
fi

if [[ -f "$DBML_PATH" ]]; then
  write_env DBML_PATH "$DBML_PATH"
else
  warn "ainda sem DBML em $DBML_PATH"
fi

# ── Stage 4: ERD ──────────────────────────────────────────────────────────
stage "ERD: gerar o desenho"

if have dbview; then
  BASE=(dbview)
else
  BASE=(node "$DBVIEW_HOME/src/cli.js")
fi

html_default="${DBML_PATH%.*}.html"
cur=$(_existing HTML_PATH || true)
if [[ -n "$cur" ]]; then
  ask HTML_PATH "Caminho do .html (saida):"
else
  ask HTML_PATH "Caminho do .html (saida) [Enter = $html_default]:"
fi
if [[ -z "$HTML_PATH" ]]; then HTML_PATH="$html_default"; fi
HTML_PATH="${HTML_PATH/#\~/$HOME}"

if [[ -f "$DBML_PATH" ]]; then
  if "${BASE[@]}" "$DBML_PATH" --out "$HTML_PATH"; then
    note "ok: $HTML_PATH"
    write_env HTML_PATH "$HTML_PATH"
  else
    warn "o dbview falhou; veja a mensagem acima"
  fi
  if confirm "Rodar tambem a analise (hubs, clusters, eixos)?"; then
    "${BASE[@]}" "$DBML_PATH" --analyze || true
  fi
else
  warn "sem DBML valido ($DBML_PATH); nada a gerar"
fi

# ── Stage 5: abrir e conferir privacidade ─────────────────────────────────
stage "Abrir e conferir privacidade (git)"

if [[ -f "$HTML_PATH" ]]; then
  open_url "file://$(_abs "$HTML_PATH")"
  step "No navegador: scroll = zoom, arrastar card, duplo-clique = enquadrar."
  step "Painel de sliders (canto inferior esquerdo) re-simula o layout ao vivo."
else
  warn "HTML nao foi gerado; nada para abrir"
fi

# Privacidade: schema de cliente nunca vai para o git.
ADD_ROOT=(); ADD_REL=()
for f in "$DBML_PATH" "$HTML_PATH"; do
  if [[ -f "$f" ]]; then
    fabs=$(_abs "$f")
    root=$(git -C "$(dirname "$fabs")" rev-parse --show-toplevel 2>/dev/null || true)
    if [[ -n "$root" ]]; then
      rel="${fabs#"$root"/}"
      if ! git -C "$root" check-ignore -q -- "$rel"; then
        warn "fora do .gitignore: $rel (repo $root)"
        ADD_ROOT+=("$root"); ADD_REL+=("$rel")
      fi
    fi
  fi
done

if (( ${#ADD_REL[@]} > 0 )); then
  if confirm "Adicionar ao .gitignore (schema de cliente nao se versiona)?"; then
    for i in "${!ADD_REL[@]}"; do
      printf '%s\n' "${ADD_REL[$i]}" >> "${ADD_ROOT[$i]}/.gitignore"
      note "ok: ${ADD_REL[$i]} em ${ADD_ROOT[$i]}/.gitignore"
    done
  else
    warn "ok — mas lembre: schema de cliente nunca vai para o git"
  fi
else
  note "nada vazando pelo git (ou arquivos fora de um repo)"
fi

finish
